scrape_configs:
  - job_name: submitter
    scrape_interval: 10s
    static_configs:
      - targets:
          - submitter:2112
  - job_name: scheduler
    scrape_interval: 10s
    static_configs:
      - targets:
          - scheduler:2112
  - job_name: worker
    scrape_interval: 10s
    static_configs:
      - targets:
          - worker:2112
  - job_name: resulter
    scrape_interval: 10s
    static_configs:
      - targets:
          - resulter:2112
  - job_name: supervisor
    scrape_interval: 10s
    static_configs:
      - targets:
          - supervisor:2112